### ISSUE TITLE
Broken Record of 2022

### ISSUE THREAD

**Issue by IAFahim** [BushraOnika/UnityCheck#2]
![image](https://github.com/user-attachments/assets/548f014c-02cd-4e44-9e16-e19be6c59c85)

![image](https://github.com/user-attachments/assets/63770564-3c00-451d-a66f-5d4eb458ed5c)

Congrats
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZThpNmdkb21ycmtkdW90enhtZzkyeXplb3J5dHltaDMzcGthZTBtbCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8592ghhkChZtlPckIT/giphy-downsized-large.gif)

**Comment by IAFahim** [comment]
Let me know when you feel confident to work on my project. Or won't get lots of money and Ammu Abbu would ask why internship not giving any money this month.

**Comment by BushraOnika** [comment]
What I have to do 🙂

**Comment by BushraOnika** [comment]
O yes my money ohooo I missed my salary give give fast
Fast fast tell

**Comment by IAFahim** [comment]
You ready? 😮‍💨 Didn't practice at all, what if I show my project and you die with pressure hmm.

**Comment by BushraOnika** [comment]
It will be more better then you don't need to give salary 😂😂

**Comment by IAFahim** [comment]
> It will be more better then you don't need to give salary 😂😂

Ehh and you won't practice and be able to go lots of places. Not better.

**Comment by BushraOnika** [comment]
Better better then I can go anywhere free of cost huh no need to work

**Comment by IAFahim** [comment]
Yes, sounds like a plan. Now get back to work 😌You up really early. Some kind of world record?

**Comment by BushraOnika** [comment]
What work I have to back?? 🙂
For your kind information I don't have any work to do

**Comment by IAFahim** [comment]
For your kind information also, I told you to practice so that you feel bit more comfortable, not my fault when you start crying in future 🙎🏻‍♂️. So you do you want to start working on my project?

**Comment by BushraOnika** [comment]
Ok ok I practice more.. See I'm kind saving your money 😌

**Comment by IAFahim** [comment]
Are you trying to help me again. Won't work.

![Shocked](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmw4dGRubnE1dGJqYW0xZGY0OXUwYzFleDVyN3YyZzJ6c2sxdnpsNSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QLBAgFEL3U4OYTKdZv/giphy.gif)

Now you are super hired. No need to practice at all, just work work.

**Comment by IAFahim** [comment]
I feel kinda bad assigning a task because you might feel sad or overwhelmed. I would try to go slow.

This is the repo:
https://github.com/IAFahim/Eternally-Spiritbound

Pull it. Open with unity 6000.0.27

**Comment by IAFahim** [comment]
You would beed to have git installed in your PC to open it. Ss it contains repository/package from other git source. So install git first.

**Comment by BushraOnika** [comment]
So rude boss I was being so kind 🥺🥺

**Comment by BushraOnika** [comment]
> I feel kinda bad assigning a task because you might feel sad or overwhelmed. I would try to go slow.
> 
> This is the repo: https://github.com/IAFahim/Eternally-Spiritbound
> 
> Pull it. Open with unity 6000.0.27

Wait what is my version I forgot 🙂

**Comment by IAFahim** [comment]
You can check from here.

![image](https://github.com/user-attachments/assets/d46ce73e-9669-4c87-a52e-88eba51b4756)

**Comment by BushraOnika** [comment]
How to pull thisss :"")
 Ok ok I found out. 
But the version is not same to mine... Mine was 6000.0.25
Have to install it 🙂

**Comment by BushraOnika** [comment]
![image](https://github.com/user-attachments/assets/b0ac1130-ad65-4519-adef-f97d22a201ed)

CAN'T PULL AT ALL :"")

**Comment by BushraOnika** [comment]
![image](https://github.com/user-attachments/assets/7ee1d42d-3077-4d43-a6fc-5e15582a5a2d)


Is it the one that you told me to open with Unity 6000.0.27????
huh too much worksssssssssssssss :"")

**Comment by IAFahim** [comment]
> ![image](https://private-user-images.githubusercontent.com/87435687/388197282-b0ac1130-ad65-4519-adef-f97d22a201ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODg2NDYsIm5iZiI6MTczMjE4ODM0NiwicGF0aCI6Ii84NzQzNTY4Ny8zODgxOTcyODItYjBhYzExMzAtYWQ2NS00NTE5LWFkZWYtZjk3ZDIyYTIwMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDExMjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZTExZWQ1ZTEzN2Q5ZTRiMzhiODFmMzY4M2M4N2NhZmFkZjk1M2YyNGVjMDIwYzc1N2RlZWQxMDNiMTEzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g6zYTvFDLMzLMyQVM3ZnMlmCq2X92iaXkBB6XtOfLYY)
> 
> CAN'T PULL AT ALL :"")

Sometimes it doesn't let you pull with little bad network. But it seems you made it. Did it take long?

**Comment by IAFahim** [comment]
> ![image](https://private-user-images.githubusercontent.com/87435687/388234727-7ee1d42d-3077-4d43-a6fc-5e15582a5a2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODg2NDYsIm5iZiI6MTczMjE4ODM0NiwicGF0aCI6Ii84NzQzNTY4Ny8zODgyMzQ3MjctN2VlMWQ0MmQtMzA3Ny00ZDQzLWE2ZmMtNWUxNTU4MmE1YTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDExMjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYTUwOTgyNjdjZDk5MzkzZGZkZWE3MTdlNWZlNDQ5Y2UzZDVjYTUzMzk3MjEzYzU0MGFjMTgxZGNlMzQzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vs6quOcNSXNgLfZSBJcVvg0y_yb3lGqMY1uPjj1jvjY)
>
> Is it the one that you told me to open with Unity 6000.0.27???? huh too much worksssssssssssssss :"")

Congrats, Yes lots of workssssssss. I see you already started looking around. Ready? On your Asus Laptop? 
_So clean looking desktop._

**Comment by BushraOnika** [comment]
Yes I like to keep neat n clean

**Comment by BushraOnika** [comment]
>
> Sometimes it doesn't let you pull with little bad network. But it seems you made it. Did it take long?

No I need to forked that then I could do the pull

**Comment by BushraOnika** [comment]
What next I have to do?? 🙂

**Comment by IAFahim** [comment]
Create islands

**Comment by IAFahim** [comment]
There are models of different type things like rocks trees. Create me 5 different types of islands. Like a island where plane takes off and stops. Smuggler islands which have dangerous boats and so on.

**Comment by IAFahim** [comment]
If you want to do something coding related you can create small text a small Jason price updater. Where price of thing like fruit and crops can be loaded and it would work in game.

**Comment by IAFahim** [comment]
But we're you able to run the game 🙂 I think I made it super confusing to even open the game up and start playing

**Comment by BushraOnika** [comment]
No I can't open the game or say play the game :"") 
There is nothing to show when I click play 🙂

**Comment by IAFahim** [comment]
The game is made up of additive scene. Like multiple scene works together to make the game. 

Open persistent scene by double clicking it: 
https://github.com/BushraOnika/Eternally-Spiritbound/blob/Changes-by-Bush/Assets/_Root/Scenes/persistent.unity

Then add village scene by dragging and dropping it on hierarchy. 

And tada that's it.

**Comment by IAFahim** [comment]
You made game with single scene right? This game uses multiple scene.

**Comment by BushraOnika** [comment]
> You made game with single scene right? This game uses multiple scene.

How this works so much confusion :""))))

**Comment by BushraOnika** [comment]
![image](https://github.com/user-attachments/assets/bb420323-ecb5-48b9-a2ce-9802a6c974a7)


how to sollve thissssss

**Comment by BushraOnika** [comment]
![image](https://github.com/user-attachments/assets/56c76299-7d36-463e-afb9-890623de1df8)



ok ok doneeee
now making islands should i create a folder named islands and create ??

**Comment by IAFahim** [comment]
Sync your fork with my update.
create islands on _root/prefabs/island

**Comment by IAFahim** [comment]
> How this works so much confusion :""))))

When you would become pro in few days you would know also.

**Comment by IAFahim** [comment]
The island should be made in boat blitz scene
